{
  "version": 3,
  "targets": {
    "net6.0": {}
  },
  "libraries": {},
  "projectFileDependencyGroups": {
    "net6.0": []
  },
  "packageFolders": {
    "/home/keshav/.nuget/packages/": {}
  },
  "project": {
    "version": "1.0.0",
    "restore": {
      "projectUniqueName": "/home/keshav/Documents/LearnCS/Chapter 27 - Exception Handling/Chapter 27 - Exception Handling.csproj",
      "projectName": "Chapter 27 - Exception Handling",
      "projectPath": "/home/keshav/Documents/LearnCS/Chapter 27 - Exception Handling/Chapter 27 - Exception Handling.csproj",
      "packagesPath": "/home/keshav/.nuget/packages/",
      "outputPath": "/home/keshav/Documents/LearnCS/Chapter 27 - Exception Handling/obj/",
      "projectStyle": "PackageReference",
      "configFilePaths": [
        "/home/keshav/.nuget/NuGet/NuGet.Config"
      ],
      "originalTargetFrameworks": [
        "net6.0"
      ],
      "sources": {
        "https://api.nuget.org/v3/index.json": {}
      },
      "frameworks": {
        "net6.0": {
          "targetAlias": "net6.0",
          "projectReferences": {}
        }
      },
      "warningProperties": {
        "warnAsError": [
          "NU1605"
        ]
      }
    },
    "frameworks": {
      "net6.0": {
        "targetAlias": "net6.0",
        "imports": [
          "net461",
          "net462",
          "net47",
          "net471",
          "net472",
          "net48"
        ],
        "assetTargetFallback": true,
        "warn": true,
        "frameworkReferences": {
          "Microsoft.NETCore.App": {
            "privateAssets": "all"
          }
        },
        "runtimeIdentifierGraphPath": "/usr/share/dotnet/sdk/6.0.300/RuntimeIdentifierGraph.json"
      }
    }
  }
}